name: Unit Tests

on:
  workflow_call:
    inputs:
      node-version:
        default: 20.x
        required: false
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true

      - name: Build Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-cache
        with:
          path: |
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install
        run: yarn install --immutable

      - name: Run unit tests
        run: yarn coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: code-coverage-report
          path: coverage/cobertura-coverage.xml
